version: '3'

services:
  app:
    build: .
    container_name: three-gltf-viewer
    working_dir: "/src"
    volumes:
      - .:/src
      - /src/node_modules
    tty: true
    ports:
      - "3045:3045"
